remote_theme: "mmistakes/minimal-mistakes"

title: "François Roussel"
name: "François Roussel"
description: "About me"

author:
  name: "François Roussel"
  avatar: "/assets/images/smiley.png"
  bio: "PhD Student"

url: "https://francoisroussel.github.io/"
baseurl: ""

locale: "fr-FR"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"

include:
  - _pages
